// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Containers() {
  return window['go']['main']['App']['Containers']();
}

export function CreateContainer(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateContainer'](arg1, arg2, arg3, arg4);
}

export function CreateTemplate(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateTemplate'](arg1, arg2, arg3);
}

export function DeleteContainer(arg1) {
  return window['go']['main']['App']['DeleteContainer'](arg1);
}

export function DeleteTemplate(arg1) {
  return window['go']['main']['App']['DeleteTemplate'](arg1);
}

export function GetTemplates(arg1) {
  return window['go']['main']['App']['GetTemplates'](arg1);
}

export function Init() {
  return window['go']['main']['App']['Init']();
}

export function OpenLink(arg1) {
  return window['go']['main']['App']['OpenLink'](arg1);
}

export function SetContainerState(arg1, arg2) {
  return window['go']['main']['App']['SetContainerState'](arg1, arg2);
}

export function XpraConnect(arg1, arg2) {
  return window['go']['main']['App']['XpraConnect'](arg1, arg2);
}
