// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {container} from '../models';
import {image} from '../models';
import {main} from '../models';

export function Containers():Promise<Array<container.Summary>>;

export function CreateContainer(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<string>;

export function CreateTemplate(arg1:string,arg2:string,arg3:string):Promise<string>;

export function DeleteContainer(arg1:string):Promise<string>;

export function DeleteTemplate(arg1:string):Promise<string>;

export function GetTemplates(arg1:boolean):Promise<Array<image.Summary>>;

export function Init():Promise<void>;

export function OpenLink(arg1:string):Promise<void>;

export function SetContainerState(arg1:string,arg2:main.ContainerState):Promise<string>;

export function XpraConnect(arg1:string,arg2:string):Promise<void>;
